import React, { useEffect, useState } from 'react';

import { Button, Container, Grid } from '@chakra-ui/react';

import Head from 'next/head';
import Image from 'next/image';

import Header from '../components/header';
import Footer from '../components/footer';

export default function Home() {
  const [currentAccount, setCurrentAccount] = useState('');
  const checkIfWalletIsConnected = async () => {
    try {
      const { ethereum } = window;

      if (!ethereum) {
        console.log('Ethereum wallet not detected - install MetaMask!');
      } else {
        console.log('We have the Ethereum object', ethereum);
      }

      // Check we're authorised on the user's wallet
      const accounts = await ethereum.request({ method: 'eth_accounts' });

      if (accounts.length > 0) {
        const account = accounts[0];
        console.log('Found an authorised account:', account);
        setCurrentAccount(account);
      } else {
        console.log('No authorised account found');
      }
    } catch (error) {
      console.log(error);
    }
  };

  const connectWallet = async () => {
    try {
      const { ethereum } = window;

      if (!ethereum) {
        alert('Get MetaMask!');
        return;
      }

      const accounts = await ethereum.request({ method: 'eth_requestAccounts' });

      console.log('Connected', accounts[0]);
      setCurrentAccount(accounts[0]);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    checkIfWalletIsConnected();
  }, []);

  return (
    <Container>
      <Head>
        <title>gm portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid templateRows="repeat(3, 1fr)" minHeight="100vh">
        <Header />

        <main>
          <div>
            {!currentAccount && (
              <Button size="lg" onClick={connectWallet}>
                Connect Wallet
              </Button>
            )}
          </div>
        </main>
      </Grid>

      <Footer />
    </Container>
  );
}
